
menu.nombre.principal=Principal
menu.nombre.estilo=Changer le style
menu.nombre.idioma=Langue
menuitem.nombre.salir=Quitter
menu.nombre.producto=Produit
menuitem.nombre.producto=Administrateur du produit
